from flask import Flask, render_template, request, redirect, url_for, jsonify, send_file
from utils.helpers import run_full_audit
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

app = Flask(__name__)

# =========================
# PAGES
# =========================

@app.route("/")
def home():
    return render_template("home.html")


@app.route("/audit", methods=["GET", "POST"])
def audit():
    if request.method == "POST":
        website = request.form.get("url")

        if not website.startswith("http"):
            website = "https://" + website

        return redirect(url_for("result", site=website))

    return render_template("audit.html")


@app.route("/result")
def result():
    site = request.args.get("site", "")
    return render_template("result.html", site=site)


@app.route("/compare")
def compare():
    return render_template("compare.html")


@app.route("/suggestions")
def suggestions():
    return render_template("suggestions.html")


@app.route("/blog")
def blog():
    return render_template("blog.html")


# =========================
# SEO AUDIT API
# =========================
@app.route("/api/audit", methods=["GET"])
def api_audit():
    site = request.args.get("site")

    if not site:
        return jsonify({"error": "Website URL missing"}), 400

    try:
        seo_result = run_full_audit(site)
        return jsonify(seo_result)

    except Exception as e:
        return jsonify({
            "error": "SEO audit failed",
            "message": str(e)
        }), 500

@app.route("/download-pdf")
def download_pdf():
    site = request.args.get("site")

    if not site:
        return "Website URL missing", 400

    data = run_full_audit(site)

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # =========================
    # HEADER
    # =========================
    pdf.setFillColorRGB(0.15, 0.39, 0.92)  # Blue bar
    pdf.rect(0, height - 80, width, 80, fill=1)

    pdf.setFillColorRGB(1, 1, 1)
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(40, height - 50, "SEO Audit Report")

    pdf.setFont("Helvetica", 11)
    pdf.drawString(40, height - 70, site)

    # =========================
    # SCORE BOX
    # =========================
    pdf.setFillColorRGB(0.95, 0.95, 0.95)
    pdf.roundRect(40, height - 160, width - 80, 60, 10, fill=1)

    pdf.setFillColorRGB(0, 0, 0)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(60, height - 135, "SEO Score")

    pdf.setFont("Helvetica-Bold", 28)
    pdf.drawRightString(width - 60, height - 140, f"{data['score']} / 100")

    # =========================
    # ISSUES SECTION
    # =========================
    y = height - 200
    pdf.setFont("Helvetica-Bold", 15)
    pdf.drawString(40, y, "SEO Issues Breakdown")
    y -= 20

    pdf.setFont("Helvetica", 11)

    for section, issues in data["issues"].items():
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(40, y, section.upper())
        y -= 15

        pdf.setFont("Helvetica", 11)

        if not issues:
            pdf.drawString(60, y, "✔ No issues found")
            y -= 15
        else:
            for issue in issues:
                pdf.drawString(60, y, f"- {issue}")
                y -= 15

        y -= 10

        if y < 80:
            pdf.showPage()
            y = height - 80
            pdf.setFont("Helvetica", 11)

    # =========================
    # FOOTER
    # =========================
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.setFillColorRGB(0.4, 0.4, 0.4)
    pdf.drawCentredString(
        width / 2,
        30,
        "Generated by SEO Rank Analyzer • College Project"
    )

    pdf.showPage()
    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="seo-audit-report.pdf",
        mimetype="application/pdf"
    )

# =========================
# RUN SERVER
# =========================
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000, debug=True)
